// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/components/triple-toggle.mdx?collection=docs&hash=1748414324377"
import * as docs_5 from "../content/docs/components/toggle.mdx?collection=docs&hash=1748414324377"
import * as docs_4 from "../content/docs/components/text-animation.mdx?collection=docs&hash=1748414324377"
import * as docs_3 from "../content/docs/components/dark-mode-toggle.mdx?collection=docs&hash=1748414324377"
import * as docs_2 from "../content/docs/(getting-started)/who-did-this.mdx?collection=docs&hash=1748414324377"
import * as docs_1 from "../content/docs/(getting-started)/installation.mdx?collection=docs&hash=1748414324377"
import * as docs_0 from "../content/docs/(getting-started)/index.mdx?collection=docs&hash=1748414324377"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"(getting-started)\\index.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/(getting-started)/index.mdx"}, data: docs_0 }, { info: {"path":"(getting-started)\\installation.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/(getting-started)/installation.mdx"}, data: docs_1 }, { info: {"path":"(getting-started)\\who-did-this.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/(getting-started)/who-did-this.mdx"}, data: docs_2 }, { info: {"path":"components\\dark-mode-toggle.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/components/dark-mode-toggle.mdx"}, data: docs_3 }, { info: {"path":"components\\text-animation.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/components/text-animation.mdx"}, data: docs_4 }, { info: {"path":"components\\toggle.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/components/toggle.mdx"}, data: docs_5 }, { info: {"path":"components\\triple-toggle.mdx","absolutePath":"D:/WebD/ui-component-library/content/docs/components/triple-toggle.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"D:/WebD/ui-component-library/content/docs/meta.json"},"data":{"title":"Vink","pages":["---Getting Started---","...(getting-started)","---Components---","...components"],"description":"Docs for Vinkers"}}, {"info":{"path":"components\\meta.json","absolutePath":"D:/WebD/ui-component-library/content/docs/components/meta.json"},"data":{"title":"Components","pages":["toggle","triple-toggle","text-animation","dark-mode-toggle"]}}, {"info":{"path":"(getting-started)\\meta.json","absolutePath":"D:/WebD/ui-component-library/content/docs/(getting-started)/meta.json"},"data":{"title":"Getting Started","pages":["index","installation","who-did-this"]}}])